"""rename pk id

Revision ID: 3b84ca1064dc
Revises: 00e790b4eb7b
Create Date: 2025-06-28 11:12:27.449395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b84ca1064dc'
down_revision: Union[str, None] = '00e790b4eb7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examinations', sa.Column('examination_id', sa.String(length=50), nullable=False))
    op.add_column('examinations', sa.Column('examination_title', sa.Text(), nullable=False))
    op.add_column('examinations', sa.Column('examination_date', sa.DateTime(), nullable=False))
    op.drop_column('examinations', 'finish_time')
    op.drop_column('examinations', 'start_time')
    op.drop_column('examinations', 'appointment_id')
    op.drop_column('examinations', 'appointment_detail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examinations', sa.Column('appointment_detail', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('examinations', sa.Column('appointment_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('examinations', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('examinations', sa.Column('finish_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('examinations', 'examination_date')
    op.drop_column('examinations', 'examination_title')
    op.drop_column('examinations', 'examination_id')
    # ### end Alembic commands ###
