"""fix versioning

Revision ID: 4fe00024af86
Revises: 639f34a65468
Create Date: 2025-06-28 23:01:21.778961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe00024af86'
down_revision: Union[str, None] = '639f34a65468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_result',
    sa.Column('lab_result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_name', sa.String(length=100), nullable=False),
    sa.Column('result_value', sa.String(length=100), nullable=False),
    sa.Column('normal_values', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('lab_date', sa.DateTime(), nullable=False),
    sa.Column('medicalhistory_id', sa.String(length=50), nullable=True),
    sa.Column('patient_mrn', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['medicalhistory_id'], ['medicalhistories.medicalhistory_id'], ),
    sa.ForeignKeyConstraint(['patient_mrn'], ['patients.patient_mrn'], ),
    sa.PrimaryKeyConstraint('lab_result_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_result')
    # ### end Alembic commands ###
