"""Initial commit

Revision ID: 63991bd9b52e
Revises: 
Create Date: 2025-06-28 14:57:00.049814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63991bd9b52e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_mrn', sa.String(length=50), nullable=False),
    sa.Column('phone_num', sa.String(length=11), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('body_part', sa.String(length=255), nullable=True),
    sa.Column('ai_ready', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('patient_mrn')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_num', sa.String(length=11), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=False),
    sa.Column('licence_num', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('appointments',
    sa.Column('appointment_id', sa.String(length=50), nullable=False),
    sa.Column('appointment_detail', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('finish_time', sa.DateTime(), nullable=False),
    sa.Column('patient_mrn', sa.String(length=50), nullable=False),
    sa.Column('doctor_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_mrn'], ['patients.patient_mrn'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('doctor_patient',
    sa.Column('doctor_id', sa.String(length=50), nullable=False),
    sa.Column('patient_mrn', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_mrn'], ['patients.patient_mrn'], ),
    sa.PrimaryKeyConstraint('doctor_id', 'patient_mrn')
    )
    op.create_table('examinations',
    sa.Column('examination_id', sa.String(length=50), nullable=False),
    sa.Column('examination_title', sa.Text(), nullable=False),
    sa.Column('examination_date', sa.DateTime(), nullable=False),
    sa.Column('patient_mrn', sa.String(length=50), nullable=False),
    sa.Column('doctor_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_mrn'], ['patients.patient_mrn'], ),
    sa.PrimaryKeyConstraint('examination_id')
    )
    op.create_table('medicalhistories',
    sa.Column('medicalhistory_id', sa.String(length=50), nullable=False),
    sa.Column('medicalhistory_date', sa.DateTime(), nullable=False),
    sa.Column('medicalhistory_title', sa.Text(), nullable=False),
    sa.Column('medicalhistory_content', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=30)), nullable=True),
    sa.Column('patient_mrn', sa.String(length=50), nullable=False),
    sa.Column('doctor_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_mrn'], ['patients.patient_mrn'], ),
    sa.PrimaryKeyConstraint('medicalhistory_id')
    )
    op.create_table('notes',
    sa.Column('note_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('patient_mrn', sa.String(length=50), nullable=False),
    sa.Column('doctor_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_mrn'], ['patients.patient_mrn'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.drop_table('medicalhistories')
    op.drop_table('examinations')
    op.drop_table('doctor_patient')
    op.drop_table('appointments')
    op.drop_table('users')
    op.drop_table('patients')
    # ### end Alembic commands ###
