"""imaging

Revision ID: cf923660a270
Revises: 02012904aabc
Create Date: 2025-06-29 11:05:00.610727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf923660a270'
down_revision: Union[str, None] = '02012904aabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imaging_subjects',
    sa.Column('subject_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('patient_mrn', sa.String(length=50), nullable=False),
    sa.Column('modality', sa.Enum('XRAY', 'MRI', name='modalitytype'), nullable=False),
    sa.Column('body_part', sa.Enum('CHEST', 'BRAIN', name='bodyparttype'), nullable=False),
    sa.Column('study_date', sa.DateTime(), nullable=True),
    sa.Column('study_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_mrn'], ['patients.patient_mrn'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('imaging_series',
    sa.Column('series_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('sequence_type', sa.Enum('T1', 'T1CE', 'T2', 'FLAIR', 'DWI', 'SEGMENTATION', 'PA', 'LATERAL', 'AP', name='sequencetype'), nullable=False),
    sa.Column('file_uri', sa.String(length=500), nullable=False),
    sa.Column('slices_dir', sa.String(length=255), nullable=True),
    sa.Column('slice_idx', sa.Integer(), nullable=True),
    sa.Column('image_resolution', sa.String(length=20), nullable=True),
    sa.Column('series_description', sa.String(length=255), nullable=True),
    sa.Column('acquisition_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['imaging_subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_table('diseases',
    sa.Column('disease_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('bounding_box', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('disease', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('class_name', sa.Enum('AORTIC_ENLARGEMENT', 'ATELECTASIS', 'CALCIFICATION', 'CARDIOMEGALY', 'CONSOLIDATION', 'ILD', 'INFILTRATION', 'LUNG_OPACITY', 'NODULE_MASS', 'OTHER_LESION', 'PLEURAL_EFFUSION', 'PLEURAL_THICKENING', 'PNEUMOTHORAX', 'PULMONARY_FIBROSIS', 'BRAIN_TUMOUR', name='diseaseclasstype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['imaging_series.series_id'], ),
    sa.PrimaryKeyConstraint('disease_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diseases')
    op.drop_table('imaging_series')
    op.drop_table('imaging_subjects')
    # ### end Alembic commands ###
